config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get '/auth/google/callback', to: 'sessions#create'
    get '/auth/failure', to: 'sessions#failure'

    get '/signin', to: redirect( path: '/auth/google' )
    get '/signout', to: 'sessions#destroy'

    get '/dashboard', to: 'projects#index'
    get '/dashboard/project/:id', to: 'projects#index'
    get '/dashboard/create', to: 'projects#index'
    # get '/api/projects', to: redirect( path: '/dashboard' )

    scope :api do
        get 'index.json', to: 'landing#fetch_json'
        get 'dashboard.json', to: 'projects#index'
        get 'user.json', to: 'users#get_current_user'
        get '/dashboard/create.json', to: 'projects#new'
        get '/dashboard/project/:id.json', to: 'projects#show'
        get '/projects/metadata.json', to: 'projects#get_metadata'
        get '/projects/:id.json', to: 'projects#get_project_information'
        resources :projects
    end

    root 'landing#index'
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
    def index; end

    def fetch_json
        render :json => { content: render_to_string( 'index', :formats => [:html], :layout => false ), title: 'Welcome', no_banner: true }
    end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.erb
<div id="splash">
    <% if current_user %>
        <span id="login-status"><%= current_user.name %> | <%= link_to 'Sign out', signout_path, class: 'no-follow' %></span>
    <% else %>
        <span id="cookie-policy">By logging in to this service via Google, you permit our use of cookies defined in our <a href="#">cookie policy</a>.</span>
    <% end %>

    <div class="min-container">
        <div class="wrapper" id="main">
            <div id="primary">
                <h1 id="title"><%= ApplicationController::SITE_NAME %></h1>
                <span id="tagline">You choose the content, we create the video</span>
            </div>
            <div id="secondary">
                <h3 id="get-started"><%= current_user and "Welcome back, #{current_user.first_name}!" or "Ready to get started?" %></h3>
                <% if current_user %>
                    <a href="dashboard" class="button" id="dashboard">Open Dashboard</a>
                <% else %>
                    <%= render 'google_auth_link', continue: request.params[:continue] %>
                <% end %>
            </div>
        </div>

        <div class="wrapper" id="bottom">
            <a href="#" id="learn-more">Learn more (WIP)</a>
        </div>
    </div>
</div>

<main>
    <div class="container" id="more">
        <strong><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus minus, magni commodi debitis, placeat dolorum non molestiae quo dignissimos nam aspernatur ipsam expedita illum? Laborum non, inventore ut cupiditate fugiat, repellendus dolore repudiandae. Placeat voluptatem culpa quia iure laboriosam consectetur fugit, consequatur deserunt. Est velit sit omnis, necessitatibus consequatur nesciunt.</p></strong>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque nihil dignissimos nostrum labore laboriosam quo cupiditate qui facere perspiciatis dolore perferendis porro accusantium necessitatibus cumque nam expedita, mollitia rerum incidunt similique iste quas? Illum tempora possimus, mollitia fuga iure molestias necessitatibus repudiandae suscipit iusto vero, provident itaque sed dolore iste eligendi incidunt atque ducimus, aspernatur amet deserunt. Totam sequi fugit deserunt omnis, doloremque. Molestiae vitae voluptatum iste autem labore placeat possimus neque sed, architecto illo aliquid maiores pariatur blanditiis, itaque nulla perspiciatis eaque ipsa. Laborum necessitatibus sit itaque nam, sint aperiam quis aliquam provident. Quaerat at nostrum id minus, nulla doloremque magni iure. Voluptatum id culpa quidem, natus earum vitae corrupti iste quisquam impedit fugiat sunt beatae nisi nesciunt deserunt blanditiis temporibus voluptas animi quia repudiandae! Ex, accusantium consectetur sapiente molestias molestiae voluptatem iusto. Exercitationem officiis corporis, ab dicta perferendis porro necessitatibus minus nostrum, aut in est nobis, ullam aliquid.</p>
    </div>
</main>